"""initial schema

Revision ID: fe95154b9ff4
Revises: 
Create Date: 2026-07-28 10:54:42.591774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe95154b9ff4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agui_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agui_snapshots')),
    sa.UniqueConstraint('scope', 'thread_id', name=op.f('uq_agui_snapshots_scope'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('cache_path', sa.Text(), nullable=True),
    sa.Column('last_fetched_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('owner', 'name', name=op.f('uq_repositories_owner'))
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_type', sa.Enum('issue', 'text', name='requirementtype', native_enum=False, length=20), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('primary_model', sa.String(length=100), nullable=False),
    sa.Column('reviewer_model', sa.String(length=100), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('intake', 'generating_spec', 'awaiting_spec_decision', 'grounding_plan', 'reviewing_plan', 'awaiting_plan_decision', 'ready_for_phase', 'executing_phase', 'pr_open', 'waiting_for_merge', 'regrounding', 'completed', 'failed', 'cancelled', name='runstate', native_enum=False, length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active_spec_revision', sa.Integer(), nullable=True),
    sa.Column('active_plan_revision', sa.Integer(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_runs_repository_id_repositories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_runs_thread_id'))
    )
    op.create_index(op.f('ix_runs_repository_id'), 'runs', ['repository_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_events_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_run_created', 'events', ['run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_run_id'), 'events', ['run_id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'executing', 'waiting_for_merge', 'merged', 'failed', name='phasestate', native_enum=False, length=30), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('worktree_path', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('merge_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_phases_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phases')),
    sa.UniqueConstraint('run_id', 'ordinal', name=op.f('uq_phases_run_id'))
    )
    op.create_index(op.f('ix_phases_run_id'), 'phases', ['run_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('issue_data', sa.JSON(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('worktree_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_source_snapshots_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots'))
    )
    op.create_index(op.f('ix_source_snapshots_run_id'), 'source_snapshots', ['run_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('specification', 'plan', 'review', 'review_ledger', 'phase_result', name='artifactkind', native_enum=False, length=40), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('rendered_markdown', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_artifacts_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_artifacts_source_snapshot_id_source_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('run_id', 'kind', 'revision', name=op.f('uq_artifacts_run_id'))
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_index('ix_artifacts_run_kind_revision', 'artifacts', ['run_id', 'kind', 'revision'], unique=False)
    op.create_index(op.f('ix_artifacts_source_snapshot_id'), 'artifacts', ['source_snapshot_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('path_or_url', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('excerpt_hash', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], name=op.f('fk_evidence_snapshot_id_source_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_snapshot_id'), 'evidence', ['snapshot_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], name=op.f('fk_operations_phase_id_phases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_operations_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_operations_idempotency_key'))
    )
    op.create_index(op.f('ix_operations_phase_id'), 'operations', ['phase_id'], unique=False)
    op.create_index(op.f('ix_operations_run_id'), 'operations', ['run_id'], unique=False)
    op.create_table('repo_locks',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], name=op.f('fk_repo_locks_phase_id_phases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repo_locks_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_repo_locks_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repository_id', name=op.f('pk_repo_locks'))
    )
    op.create_index(op.f('ix_repo_locks_phase_id'), 'repo_locks', ['phase_id'], unique=False)
    op.create_index(op.f('ix_repo_locks_run_id'), 'repo_locks', ['run_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('decision_type', sa.Enum('accept', 'refine', 'start_phase', 'cancel', name='decisiontype', native_enum=False, length=30), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_decisions_artifact_id_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], name=op.f('fk_decisions_phase_id_phases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_decisions_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_repo_locks_run_id'), table_name='repo_locks')
    op.drop_index(op.f('ix_repo_locks_phase_id'), table_name='repo_locks')
    op.drop_table('repo_locks')
    op.drop_index(op.f('ix_operations_run_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_phase_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_evidence_snapshot_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_artifacts_source_snapshot_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_run_kind_revision', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_source_snapshots_run_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_phases_run_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_index(op.f('ix_events_run_id'), table_name='events')
    op.drop_index('ix_events_run_created', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_runs_repository_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('repositories')
    op.drop_table('agui_snapshots')
    # ### end Alembic commands ###

